# Generated by Django 5.1 on 2025-11-17 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20251117_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='problems_us_user_id_735adb_idx',
            old_name='user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='problems_us_problem_4fcae3_idx',
            old_name='problem_idx',
        ),
        migrations.AddField(
            model_name='problem',
            name='ac_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='ai_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='has_editorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='submission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.tag'),
        ),
    ]
