# Generated by Django 5.1 on 2025-11-21 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('access_mode', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('hidden', 'Hidden'), ('contest_only', 'Only after contest finish')], default='hidden', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_meta', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
