# Generated by Django 5.1 on 2025-11-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problemeditorial_editorialpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemeditorial',
            name='access_mode',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('hidden', 'Hidden'), ('contest_only', 'Only after contest')], default='hidden', max_length=20),
        ),
    ]
