# Generated by Django 5.1 on 2026-07-29 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_question_id",
                    models.CharField(db_index=True, max_length=160, unique=True),
                ),
                ("source_code", models.CharField(blank=True, max_length=160)),
                ("question_type", models.CharField(db_index=True, max_length=32)),
                ("cognitive_level", models.CharField(db_index=True, max_length=32)),
                ("difficulty", models.PositiveSmallIntegerField(db_index=True)),
                ("competency", models.CharField(blank=True, max_length=16)),
                ("language", models.CharField(default="vi", max_length=16)),
                ("source_status", models.CharField(db_index=True, max_length=32)),
                ("process_status", models.CharField(db_index=True, max_length=64)),
                ("use_purpose", models.CharField(db_index=True, max_length=64)),
                ("shuffle_allowed", models.BooleanField(default=False)),
                (
                    "duplicate_family_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "estimated_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("is_available", models.BooleanField(db_index=True, default=False)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("source_question_id",),
            },
        ),
        migrations.CreateModel(
            name="BankSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=160, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("drive_url", models.URLField(blank=True, max_length=1000)),
                ("folder_path", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("source_status", models.CharField(blank=True, max_length=32)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="CurriculumNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=128, unique=True)),
                ("grade", models.PositiveSmallIntegerField(db_index=True)),
                ("subject", models.CharField(max_length=100)),
                ("program_version", models.CharField(max_length=100)),
                ("topic_code", models.CharField(max_length=32)),
                ("topic_name", models.CharField(max_length=500)),
                ("order_no", models.PositiveIntegerField(default=0)),
                ("source_status", models.CharField(max_length=32)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("grade", "order_no", "source_id"),
            },
        ),
        migrations.CreateModel(
            name="AssessmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=160)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("sync_bank", "Can synchronize the assessment bank"),
                    ("view_dashboard", "Can view assessment dashboard"),
                    ("view_audit_log", "Can view assessment audit log"),
                    ("manage_blueprint", "Can manage assessment blueprints"),
                    ("approve_blueprint", "Can approve assessment blueprints"),
                    ("manage_scoring", "Can manage assessment scoring"),
                    ("create_exam", "Can create assessment exams"),
                    ("publish_exam", "Can publish assessment exams"),
                    ("manage_participants", "Can manage assessment participants"),
                    ("view_results", "Can view assessment results"),
                    ("release_results", "Can release assessment results"),
                    ("release_answers", "Can release assessment answers"),
                    ("export_exam", "Can export assessment exams"),
                    ("export_blueprint", "Can export assessment blueprints"),
                    ("manage_access", "Can manage assessment access"),
                    ("invalidate_attempt", "Can invalidate assessment attempts"),
                    ("regrade_attempts", "Can regrade assessment attempts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BankQuestionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_version", models.CharField(max_length=64)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("stem_text", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("statements", models.JSONField(blank=True, default=list)),
                ("protected_answer", models.JSONField()),
                ("explanation_source_id", models.CharField(blank=True, max_length=160)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="assessment.bankquestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-synced_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_questions",
                to="assessment.bankquestionrevision",
            ),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="assessment.curriculumnode",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=160, unique=True)),
                ("code", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("cognitive_level", models.CharField(max_length=32)),
                ("source_status", models.CharField(max_length=32)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcomes",
                        to="assessment.curriculumnode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="assessment.curriculumoutcome",
            ),
        ),
        migrations.CreateModel(
            name="QuestionAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_page", models.CharField(blank=True, max_length=128)),
                ("source_section", models.CharField(blank=True, max_length=255)),
                ("source_ref", models.TextField(blank=True)),
                ("license_note", models.TextField(blank=True)),
                ("source_status", models.CharField(blank=True, max_length=32)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assessment.bankquestion",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_assets",
                        to="assessment.banksourcefile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("DRY_RUN", "Dry run"), ("APPLY", "Apply")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=1000)),
                ("source_sha256", models.CharField(blank=True, max_length=64)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="bankquestionrevision",
            constraint=models.UniqueConstraint(
                fields=("question", "content_hash"),
                name="assessment_unique_question_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionasset",
            constraint=models.UniqueConstraint(
                fields=("question", "source_file"),
                name="assessment_unique_question_source",
            ),
        ),
    ]
