# Generated by Django 5.1 on 2026-07-29 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("instructions", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BlueprintSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("question_type", models.CharField(max_length=32)),
                ("cognitive_level", models.CharField(blank=True, max_length=32)),
                ("difficulty", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("competency", models.CharField(blank=True, max_length=16)),
                ("quantity", models.PositiveIntegerField()),
                ("score_per_item", models.DecimalField(decimal_places=3, max_digits=8)),
                ("required_tags", models.JSONField(blank=True, default=list)),
                ("excluded_tags", models.JSONField(blank=True, default=list)),
                ("requires_graduation_eligibility", models.BooleanField(default=False)),
                ("allow_previously_used", models.BooleanField(default=True)),
                ("max_usage_count", models.PositiveIntegerField(blank=True, null=True)),
                ("reuse_cooldown_days", models.PositiveIntegerField(default=0)),
                ("shortage_priority", models.PositiveIntegerField(default=0)),
                (
                    "curriculum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_slots",
                        to="assessment.curriculumnode",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_slots",
                        to="assessment.curriculumoutcome",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="assessment.blueprintsection",
                    ),
                ),
            ],
            options={
                "ordering": ("section__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BlueprintVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("expected_question_count", models.PositiveIntegerField()),
                (
                    "expected_total_score",
                    models.DecimalField(decimal_places=3, max_digits=8),
                ),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("source_blueprint_id", models.CharField(blank=True, max_length=160)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("validation_report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_blueprint_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blueprint_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("blueprint", "-version"),
            },
        ),
        migrations.AddField(
            model_name="blueprintsection",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="assessment.blueprintversion",
            ),
        ),
        migrations.CreateModel(
            name="ExamBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("exam_type", models.CharField(db_index=True, max_length=64)),
                ("grade", models.PositiveSmallIntegerField(db_index=True)),
                ("subject", models.CharField(default="Tin học", max_length=100)),
                ("semester", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Nháp"),
                            ("APPROVED", "Đã duyệt"),
                            ("LOCKED", "Đã khóa"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_assessment_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessment_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blueprintversion",
            name="blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="assessment.examblueprint",
            ),
        ),
        migrations.CreateModel(
            name="ScoringScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scoring_schemes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringSchemeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("total_score", models.DecimalField(decimal_places=3, max_digits=8)),
                ("rounding_digits", models.PositiveSmallIntegerField(default=2)),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("source_policy_id", models.CharField(blank=True, max_length=160)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scoring_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="assessment.scoringscheme",
                    ),
                ),
            ],
            options={
                "ordering": ("scheme", "-version"),
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_type", models.CharField(max_length=32)),
                ("rule_code", models.CharField(max_length=100)),
                ("max_score", models.DecimalField(decimal_places=3, max_digits=8)),
                ("configuration", models.JSONField(default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="assessment.scoringschemeversion",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="blueprintsection",
            constraint=models.UniqueConstraint(
                fields=("version", "code"), name="assessment_unique_section_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintversion",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "version"),
                name="assessment_unique_blueprint_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringschemeversion",
            constraint=models.UniqueConstraint(
                fields=("scheme", "version"), name="assessment_unique_scoring_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringrule",
            constraint=models.UniqueConstraint(
                fields=("version", "question_type"),
                name="assessment_unique_scoring_type",
            ),
        ),
    ]
