# Generated by Django 5.1 on 2026-07-29 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_blueprintsection_blueprintslot_blueprintversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("PRACTICE", "Luyện tập"),
                            ("REGULAR", "Kiểm tra thường xuyên"),
                            ("PERIODIC", "Kiểm tra định kỳ"),
                            ("GRADUATION", "Thi thử tốt nghiệp"),
                            ("CUSTOM", "Tùy chỉnh"),
                        ],
                        max_length=32,
                    ),
                ),
                ("opens_at", models.DateTimeField(db_index=True)),
                ("closes_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                (
                    "attempt_result_mode",
                    models.CharField(
                        choices=[
                            ("FIRST", "Lần đầu"),
                            ("LAST", "Lần cuối"),
                            ("HIGHEST", "Cao nhất"),
                            ("AVERAGE", "Trung bình"),
                            ("TEACHER_SELECTED", "Giáo viên chọn"),
                        ],
                        default="HIGHEST",
                        max_length=32,
                    ),
                ),
                ("next_attempt_delay_minutes", models.PositiveIntegerField(default=0)),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_options", models.BooleanField(default=True)),
                ("code_count", models.PositiveIntegerField(default=1)),
                (
                    "generation_mode",
                    models.CharField(
                        choices=[
                            ("COMMON_EXAM", "Đề chung"),
                            ("MULTIPLE_EQUIVALENT_CODES", "Nhiều mã tương đương"),
                            ("INDIVIDUAL_EXAM", "Đề cá nhân"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "score_release_mode",
                    models.CharField(
                        choices=[
                            ("NEVER", "Không bao giờ"),
                            ("IMMEDIATELY_AFTER_SUBMIT", "Ngay sau khi nộp"),
                            ("AFTER_USER_FINISHES_ALL_ATTEMPTS", "Sau khi hết lượt"),
                            ("AFTER_EXAM_CLOSES", "Sau khi đóng kỳ thi"),
                            ("AT_SPECIFIC_TIME", "Tại thời điểm cấu hình"),
                            ("MANUAL_RELEASE", "Công bố thủ công"),
                        ],
                        default="MANUAL_RELEASE",
                        max_length=40,
                    ),
                ),
                (
                    "answer_release_mode",
                    models.CharField(
                        choices=[
                            ("NEVER", "Không bao giờ"),
                            ("IMMEDIATELY_AFTER_SUBMIT", "Ngay sau khi nộp"),
                            ("AFTER_USER_FINISHES_ALL_ATTEMPTS", "Sau khi hết lượt"),
                            ("AFTER_EXAM_CLOSES", "Sau khi đóng kỳ thi"),
                            ("AT_SPECIFIC_TIME", "Tại thời điểm cấu hình"),
                            ("MANUAL_RELEASE", "Công bố thủ công"),
                        ],
                        default="NEVER",
                        max_length=40,
                    ),
                ),
                ("answer_release_at", models.DateTimeField(blank=True, null=True)),
                ("release_solutions", models.BooleanField(default=False)),
                ("allow_exam_download", models.BooleanField(default=False)),
                ("allow_blueprint_download", models.BooleanField(default=False)),
                ("allow_review", models.BooleanField(default=False)),
                ("allow_retry_after_answers", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Nháp"),
                            ("SCHEDULED", "Đã lên lịch"),
                            ("OPEN", "Đang mở"),
                            ("CLOSED", "Đã đóng"),
                            ("PUBLISHED", "Đã công bố"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blueprint_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_sessions",
                        to="assessment.blueprintversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scoring_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_sessions",
                        to="assessment.scoringschemeversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("make_up_allowed", models.BooleanField(default=False)),
                ("allow_after_deadline", models.BooleanField(default=False)),
                ("extra_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "max_attempts_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="assessment.examsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("seed", models.CharField(max_length=128)),
                ("total_score", models.DecimalField(decimal_places=3, max_digits=8)),
                ("validation_report", models.JSONField(default=dict)),
                ("exam_hash", models.CharField(db_index=True, max_length=64)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "blueprint_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment.blueprintversion",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_assessment_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scoring_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment.scoringschemeversion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_exams",
                        to="assessment.examsession",
                    ),
                ),
            ],
            options={
                "ordering": ("session", "code"),
            },
        ),
        migrations.CreateModel(
            name="GeneratedExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("question_id_snapshot", models.CharField(max_length=160)),
                ("source_version_snapshot", models.CharField(max_length=64)),
                ("stem_snapshot", models.TextField()),
                ("options_snapshot", models.JSONField(blank=True, default=list)),
                ("statements_snapshot", models.JSONField(blank=True, default=list)),
                ("protected_answer_snapshot", models.TextField()),
                ("option_order", models.JSONField(blank=True, default=list)),
                ("score", models.DecimalField(decimal_places=3, max_digits=8)),
                ("content_hash_snapshot", models.CharField(max_length=64)),
                (
                    "bank_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment.bankquestion",
                    ),
                ),
                (
                    "bank_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment.bankquestionrevision",
                    ),
                ),
                (
                    "blueprint_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessment.blueprintslot",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="assessment.generatedexam",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="GeneratedExamAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_id_snapshot", models.CharField(max_length=160)),
                ("name_snapshot", models.CharField(max_length=500)),
                ("mime_type_snapshot", models.CharField(blank=True, max_length=255)),
                ("source_page_snapshot", models.CharField(blank=True, max_length=128)),
                ("checksum_snapshot", models.CharField(blank=True, max_length=128)),
                (
                    "exam_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assessment.generatedexamquestion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="examsession",
            index=models.Index(
                fields=["status", "opens_at", "closes_at"],
                name="assessment_session_window_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="examparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="assessment_unique_exam_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedexam",
            constraint=models.UniqueConstraint(
                fields=("session", "code"), name="assessment_unique_exam_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedexamquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "order"), name="assessment_unique_exam_question_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedexamquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "bank_question"), name="assessment_unique_exam_question"
            ),
        ),
    ]
