# Generated by Django 5.1 on 2026-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_examsession_examparticipant_generatedexam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintslot",
            name="required_process_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="demo_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_download_blueprint",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_download_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_view_answers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_view_solutions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examsession",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="scoringscheme",
            name="demo_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="scoringscheme",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
