# Generated by Django 5.1 on 2026-07-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_blueprintslot_required_process_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blueprintslot",
            name="required_process_status",
        ),
        migrations.RemoveField(
            model_name="examblueprint",
            name="demo_key",
        ),
        migrations.RemoveField(
            model_name="examblueprint",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="examparticipant",
            name="can_access",
        ),
        migrations.RemoveField(
            model_name="examparticipant",
            name="can_download_blueprint",
        ),
        migrations.RemoveField(
            model_name="examparticipant",
            name="can_download_exam",
        ),
        migrations.RemoveField(
            model_name="examparticipant",
            name="can_view_answers",
        ),
        migrations.RemoveField(
            model_name="examparticipant",
            name="can_view_solutions",
        ),
        migrations.RemoveField(
            model_name="examsession",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="scoringscheme",
            name="demo_key",
        ),
        migrations.RemoveField(
            model_name="scoringscheme",
            name="is_demo",
        ),
    ]
