# Generated by Django 5.1 on 2026-07-29 13:29

from django.db import migrations, models


DEMO_SESSION_SLUGS = (
    "assessment-demo-practice",
    "assessment-demo-periodic",
    "assessment-demo-graduation",
    "assessment-demo-access",
)


def backfill_demo_session_keys(apps, schema_editor):
    ExamSession = apps.get_model("assessment", "ExamSession")
    for slug in DEMO_SESSION_SLUGS:
        ExamSession.objects.filter(
            slug=slug,
            is_demo=True,
            demo_key__isnull=True,
        ).update(demo_key=slug)


def clear_backfilled_demo_session_keys(apps, schema_editor):
    ExamSession = apps.get_model("assessment", "ExamSession")
    ExamSession.objects.filter(
        slug__in=DEMO_SESSION_SLUGS,
        is_demo=True,
        demo_key__in=DEMO_SESSION_SLUGS,
    ).update(demo_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_remove_blueprintslot_required_process_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintslot",
            name="required_process_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="demo_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_download_blueprint",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_download_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_view_answers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examparticipant",
            name="can_view_solutions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examsession",
            name="demo_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="scoringscheme",
            name="demo_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="scoringscheme",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(
            backfill_demo_session_keys,
            clear_backfilled_demo_session_keys,
        ),
    ]
