# Generated by Django 5.1 on 2026-07-30 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_phase4_configuration(apps, schema_editor):
    ExamSession = apps.get_model("assessment", "ExamSession")
    GeneratedExam = apps.get_model("assessment", "GeneratedExam")
    mode_map = {
        "COMMON_EXAM": "FIXED_EXAM",
        "MULTIPLE_EQUIVALENT_CODES": "ON_DEMAND_CODE_POOL",
        "INDIVIDUAL_EXAM": "ON_DEMAND_INDIVIDUAL",
    }
    for old_mode, new_mode in mode_map.items():
        ExamSession.objects.filter(generation_mode=old_mode).update(generation_mode=new_mode)
    # Before ExamAttempt existed every stored exam came from Phase 4 pre-generation.
    # Preserve it temporarily as an already-expired preview so operators can inspect
    # and remove it with cleanup_assessment_phase4_legacy after a dry-run.
    GeneratedExam.objects.filter(purpose__isnull=True).update(
        purpose="PREVIEW", expires_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_restore_assessment_demo_and_access_fields"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "Đang làm"),
                            ("SUBMITTED", "Đã nộp"),
                            ("AUTO_SUBMITTED", "Tự động nộp"),
                            ("GRADED", "Đã chấm"),
                            ("INVALIDATED", "Vô hiệu hóa"),
                            ("EXPIRED", "Hết hạn"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("invalidation_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="generatedexam",
            name="assessment_unique_exam_code",
        ),
        migrations.AddField(
            model_name="examsession",
            name="access_grades",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="examsession",
            name="access_groups",
            field=models.ManyToManyField(
                blank=True, related_name="assessment_sessions", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="examsession",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("ALL_USERS", "Mọi tài khoản"),
                    ("SELECTED_GROUPS", "Nhóm được chọn"),
                    ("SELECTED_GRADES", "Khối được chọn"),
                    ("SELECTED_USERS", "Tài khoản được chọn"),
                ],
                default="ALL_USERS",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="generatedexam",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedexam",
            name="purpose",
            field=models.CharField(
                choices=[("ATTEMPT", "Attempt"), ("PREVIEW", "Preview")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("ON_DEMAND_INDIVIDUAL", "Sinh riêng khi bắt đầu"),
                    ("ON_DEMAND_CODE_POOL", "Cấp mã từ nhóm khi bắt đầu"),
                    ("FIXED_EXAM", "Đề cố định"),
                ],
                default="ON_DEMAND_INDIVIDUAL",
                max_length=40,
            ),
        ),
        migrations.RunPython(migrate_phase4_configuration, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="generatedexam",
            name="purpose",
            field=models.CharField(
                choices=[("ATTEMPT", "Attempt"), ("PREVIEW", "Preview")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="generatedexamasset",
            name="exam_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="assessment.generatedexamquestion",
            ),
        ),
        migrations.AlterField(
            model_name="generatedexamquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.generatedexam",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedexam",
            constraint=models.CheckConstraint(
                condition=models.Q(purpose__in=("ATTEMPT", "PREVIEW")),
                name="assessment_generated_exam_valid_purpose",
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="generated_exam",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt",
                to="assessment.generatedexam",
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="assessment.examsession",
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "session", "attempt_number"),
                name="assessment_unique_attempt_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("user", "session"),
                name="assessment_one_in_progress_attempt",
            ),
        ),
    ]
