# Generated by Django 5.1 on 2026-07-30 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_on_demand_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="data_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField(blank=True, default=dict)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessment.examattempt",
                    ),
                ),
                (
                    "exam_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_answers",
                        to="assessment.generatedexamquestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "exam_question"),
                        name="assessment_unique_attempt_answer",
                    )
                ],
            },
        ),
    ]
