# Generated by Django 5.1 on 2026-08-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0015_verify_blueprint_group_schema"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsession",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("ALL_USERS", "Mọi tài khoản"),
                    ("SELECTED_GROUPS", "Nhóm được chọn"),
                    ("SELECTED_GRADES", "Khối được chọn"),
                    ("ACCESS_GRANTS", "Cấp quyền theo người dùng / nhóm"),
                ],
                default="ALL_USERS",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ExamAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_mode",
                    models.CharField(
                        choices=[
                            ("ATTEMPTS", "Theo số lượt làm"),
                            ("VALIDITY", "Theo thời gian hiệu lực"),
                            ("BOTH", "Theo số lượt và thời gian hiệu lực"),
                        ],
                        default="ATTEMPTS",
                        max_length=16,
                    ),
                ),
                ("max_attempts", models.PositiveIntegerField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_access_grants",
                        to="auth.group",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="assessment.examsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("session", "user", "group"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="assessment_grant_exactly_one_subject",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("session", "user"),
                        name="assessment_unique_session_user_grant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("group__isnull", False)),
                        fields=("session", "group"),
                        name="assessment_unique_session_group_grant",
                    ),
                ],
            },
        ),
    ]
