# Generated by Django 5.1 on 2026-08-03 00:13

from django.db import migrations, models


def copy_long_metadata(apps, schema_editor):
    BankSourceFile = apps.get_model("assessment", "BankSourceFile")
    for source in BankSourceFile.objects.only("pk", "source_metadata").iterator():
        metadata = source.source_metadata or {}
        source.source_group = str(metadata.get("source_group") or "")
        source.note = str(metadata.get("note") or "")
        source.save(update_fields=("source_group", "note"))


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0016_alter_examsession_access_mode_examaccessgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="banksourcefile",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="banksourcefile",
            name="source_group",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(copy_long_metadata, migrations.RunPython.noop),
    ]
