# Generated by Django 5.1 on 2026-08-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0017_banksourcefile_note_banksourcefile_source_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="examaccessgrant",
            name="allow_download",
            field=models.BooleanField(
                default=False,
                help_text="Cho phép tải gói ZIP gồm đề, đáp án, ma trận và đặc tả cho người dùng/nhóm được cấp quyền này.",
            ),
        ),
    ]
