# Generated by Django 5.1 on 2026-08-05 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_attempt_usage(apps, schema_editor):
    ExamAttempt = apps.get_model("assessment", "ExamAttempt")
    ExamUsageRecord = apps.get_model("assessment", "ExamUsageRecord")
    rows = []
    now = timezone.now()
    for attempt in ExamAttempt.objects.exclude(status="INVALIDATED").iterator():
        rows.append(ExamUsageRecord(
            user_id=attempt.user_id, exam_session_id=attempt.session_id,
            usage_type="ONLINE_ATTEMPT", status="COMMITTED",
            exam_attempt_id=attempt.pk,
            idempotency_key=f"backfill-online-{attempt.pk}",
            created_at=attempt.started_at or now,
            committed_at=attempt.started_at or now,
        ))
    ExamUsageRecord.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0018_exam_access_grant_allow_download"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamResourcePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seed", models.CharField(max_length=128)),
                ("question_snapshot", models.JSONField(blank=True, default=list)),
                ("answer_snapshot", models.JSONField(blank=True, default=dict)),
                ("scoring_snapshot", models.JSONField(blank=True, default=dict)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang tạo"),
                            ("READY", "Sẵn sàng"),
                            ("FAILED", "Lỗi"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_packages",
                        to="assessment.examblueprint",
                    ),
                ),
                (
                    "blueprint_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_packages",
                        to="assessment.blueprintversion",
                    ),
                ),
                (
                    "generated_exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_package",
                        to="assessment.generatedexam",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_packages",
                        to="assessment.examsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_resource_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("ONLINE_ATTEMPT", "Làm bài trực tuyến"),
                            ("DOWNLOAD_PACKAGE", "Tạo đề tải"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Đã giữ lượt"),
                            ("COMMITTED", "Đã dùng lượt"),
                            ("RELEASED", "Đã hoàn lượt"),
                        ],
                        db_index=True,
                        default="RESERVED",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_record",
                        to="assessment.examattempt",
                    ),
                ),
                (
                    "exam_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_records",
                        to="assessment.examsession",
                    ),
                ),
                (
                    "resource_package",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_record",
                        to="assessment.examresourcepackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "exam_session", "status"],
                        name="assessment_usage_quota_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "exam_session", "idempotency_key"),
                        name="assessment_unique_usage_idempotency",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_attempt_usage, noop_reverse),
    ]
