# Generated by Django 5.1 on 2026-08-07 10:46

from django.db import migrations, models


def convert_runtime_trials_to_access_grants(apps, schema_editor):
    """Preserve any brief 0020 runtime usage without retaining a second quota."""
    Usage = apps.get_model("assessment", "ExamUsageRecord")
    Grant = apps.get_model("assessment", "ExamAccessGrant")
    Session = apps.get_model("assessment", "ExamSession")
    Entitlement = apps.get_model("assessment", "TrialEntitlement")
    rows = Usage.objects.exclude(trial_entitlement_id=None).values_list(
        "trial_entitlement_id", "user_id", "exam_session_id",
    ).distinct()
    for entitlement_id, user_id, session_id in rows.iterator():
        quota = Entitlement.objects.filter(pk=entitlement_id).values_list(
            "quota_total", flat=True,
        ).first() or 3
        Grant.objects.get_or_create(
            session_id=session_id,
            user_id=user_id,
            defaults={
                "limit_mode": "ATTEMPTS",
                "max_attempts": quota,
                "is_active": True,
            },
        )
        Session.objects.filter(pk=session_id).update(allow_signup_trial=True)


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0020_trialentitlement_trialdevice_trialauditevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="allow_signup_trial",
            field=models.BooleanField(
                default=False,
                help_text="Tự động cấp quyền 3 lượt cho tài khoản mới đủ điều kiện dùng thử.",
            ),
        ),
        migrations.RunPython(convert_runtime_trials_to_access_grants, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="examusagerecord",
            name="trial_entitlement",
        ),
        migrations.RemoveField(
            model_name="trialentitlement",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="trialentitlement",
            name="first_used_at",
        ),
        migrations.RemoveField(
            model_name="trialentitlement",
            name="last_used_at",
        ),
        migrations.RemoveField(
            model_name="trialentitlement",
            name="quota_total",
        ),
    ]
