# Generated by Django 5.1 on 2026-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0023_generatedexamquestion_statement_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankquestion",
            name="ai_component",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="grad_ai_task",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="grad_nls_task",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="graduation_gate",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="import_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="nls_frame",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="nls_level",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bankquestion",
            name="nls_primary",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
