# Generated by Django 5.1 on 2026-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0025_repair_bank_v2_schema_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintslot",
            name="source_cell_id",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name="blueprintslot",
            name="source_slot_id",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name="blueprintslot",
            name="source_slot_no",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="blueprint_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="blueprint_slot_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="blueprint_slot_no_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="blueprint_version_snapshot",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="curriculum_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="family_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="generatedexamquestion",
            name="outcome_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddConstraint(
            model_name="blueprintslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_slot_id", ""), _negated=True),
                fields=("section", "source_slot_id"),
                name="assessment_unique_version_source_slot",
            ),
        ),
    ]
