# Generated by Django 5.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auto_approve", models.BooleanField(default=False, help_text="Tài khoản tạo sau khi bật tùy chọn này sẽ được kích hoạt ngay.", verbose_name="Tự động phê duyệt đăng ký mới")),
            ],
            options={"verbose_name": "Cài đặt phê duyệt", "verbose_name_plural": "Cài đặt phê duyệt"},
        ),
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Chờ phê duyệt"), ("approved", "Đã phê duyệt"), ("rejected", "Đã từ chối")], default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng ký")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Ngày xử lý")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_registrations", to=settings.AUTH_USER_MODEL, verbose_name="Người xử lý")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="registration_request", to=settings.AUTH_USER_MODEL, verbose_name="Tài khoản")),
            ],
            options={"verbose_name": "Đăng ký tài khoản", "verbose_name_plural": "Quản lý đăng ký", "ordering": ("-created_at",)},
        ),
    ]
