# Generated by Django 5.1 on 2025-11-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_practicesession_options_and_more'),
        ('submissions', '0003_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='practice_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.practicesession'),
        ),
    ]
