# Generated by Django 5.1 on 2025-11-20 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '000X_add_stateful_robot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arenaprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='arenaprogress',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.arenagame'),
        ),
        migrations.AlterField(
            model_name='arenaprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
