# Generated by Django 5.1 on 2025-11-20 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arenagame',
            name='min_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arenagame',
            name='robot_mode',
            field=models.CharField(blank=True, choices=[('egg', 'Egg – Trứng'), ('chick', 'Chick – Gà con'), ('teen', 'Teen – Gà choai')], max_length=20),
        ),
        migrations.AddField(
            model_name='arenarun',
            name='mode',
            field=models.CharField(blank=True, choices=[('egg', 'Egg'), ('chick', 'Chick'), ('teen', 'Teen')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserRobotProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('passed_egg', models.BooleanField(default=False)),
                ('passed_chick', models.BooleanField(default=False)),
                ('passed_teen', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robot_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
