# Generated by Django 5.1 on 2025-11-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_arenagame_min_level_arenagame_robot_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arenagame',
            name='min_level',
        ),
        migrations.RemoveField(
            model_name='arenagame',
            name='robot_mode',
        ),
        migrations.RemoveField(
            model_name='arenarun',
            name='mode',
        ),
        migrations.CreateModel(
            name='ArenaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score_egg', models.IntegerField(default=0)),
                ('best_score_chick', models.IntegerField(default=0)),
                ('best_score_teen', models.IntegerField(default=0)),
                ('egg_passed', models.BooleanField(default=False)),
                ('chick_passed', models.BooleanField(default=False)),
                ('teen_passed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='arena.arenagame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.DeleteModel(
            name='UserRobotProgress',
        ),
    ]
