services:
  - type: web
    name: dmoj-lite
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn oj.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
