# oj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render


def home(request):
    stages = [
        {"stage": "Bắt đầu",
         "desc": "Làm quen lập trình và tư duy logic cơ bản.",
         "examples": ["Nhập xuất", "Vòng lặp", "Điều kiện"],
         "tag": "basic", "color": "sky"},
        {"stage": "Hai con trỏ",
         "desc": "Tư duy tìm kiếm nhanh, tối ưu hoá dãy và mảng.",
         "examples": ["Hai con trỏ", "Sliding Window", "Prefix sum"],
         "tag": "twopointers", "color": "indigo"},
        {"stage": "Cấu trúc dữ liệu",
         "desc": "Hiểu và áp dụng các cấu trúc dữ liệu phổ biến.",
         "examples": ["Stack & Queue", "Linked List", "Set & Map"],
         "tag": "datastructures", "color": "amber"},
        {"stage": "Thuật toán cơ bản",
         "desc": "Các kỹ thuật tìm kiếm, sắp xếp, đệ quy.",
         "examples": ["Sort", "Search", "Recursion"],
         "tag": "algorithms", "color": "emerald"},
        {"stage": "Đệ quy & Quay lui",
         "desc": "Học cách chia nhỏ vấn đề và sinh nghiệm.",
         "examples": ["Quay lui", "Nhánh cận", "Sinh tổ hợp"],
         "tag": "backtracking", "color": "pink"},
        {"stage": "Quy hoạch động",
         "desc": "Tư duy tối ưu hóa bài toán phức tạp.",
         "examples": ["DP cơ bản", "Knapsack", "Dãy con tăng"],
         "tag": "dp", "color": "purple"},
        {"stage": "Chia để trị",
         "desc": "Kỹ thuật xử lý nhanh với chia nhỏ dữ liệu.",
         "examples": ["Merge sort", "Binary search", "Divide & conquer"],
         "tag": "divideconquer", "color": "teal"},
        {"stage": "Đồ thị cơ bản",
         "desc": "Làm quen với đỉnh, cạnh và các thuật toán duyệt.",
         "examples": ["DFS", "BFS", "Connected Components"],
         "tag": "graph", "color": "orange"},
        {"stage": "Đồ thị nâng cao",
         "desc": "Giải quyết các bài toán khó với Graph nâng cao.",
         "examples": ["Dijkstra", "Floyd", "Toposort"],
         "tag": "graphadv", "color": "rose"},
        {"stage": "Cây & nhị phân",
         "desc": "Nắm vững cây nhị phân và ứng dụng.",
         "examples": ["Tree traversal", "Binary Search Tree", "Segment Tree"],
         "tag": "tree", "color": "green"},
        {"stage": "Cây nâng cao",
         "desc": "Hiểu cấu trúc và ứng dụng cây phức tạp.",
         "examples": ["Fenwick Tree", "HLD", "Trie"],
         "tag": "treeadv", "color": "lime"},
        {"stage": "Lý thuyết số",
         "desc": "Các bài toán về chia hết, ước, modulo.",
         "examples": ["GCD/LCM", "Modulo", "Sieve of Eratosthenes"],
         "tag": "math", "color": "cyan"},
        {"stage": "Chuỗi & Xử lý ký tự",
         "desc": "Kỹ thuật thao tác chuỗi và pattern.",
         "examples": ["KMP", "Hash String", "Z-function"],
         "tag": "string", "color": "fuchsia"},
        {"stage": "Nâng cao & Ứng dụng",
         "desc": "Vận dụng tổng hợp và phát triển kỹ năng.",
         "examples": ["Bài thi", "Tối ưu code", "Phân tích độ phức tạp"],
         "tag": "advanced", "color": "stone"},
    ]
    return render(request, "home.html", {"stages": stages})


urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("problems/", include("problems.urls")),
    path("submissions/", include("submissions.urls")),
    path("contests/", include("contests.urls")),
]
