# Generated by Django 5.1 on 2025-11-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_practicesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='practicesession',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
