# Generated by Django 5.1 on 2025-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_practicesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='practice_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='practice_time',
            field=models.PositiveIntegerField(default=10800, help_text='Thời gian làm PRACTICE (giây). Ví dụ 3600 = 60 phút'),
        ),
    ]
