# Generated by Django 5.1 on 2025-11-21 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_practice_open_contest_practice_time'),
        ('problems', '0005_alter_problemeditorial_access_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='practice_time',
            field=models.PositiveIntegerField(default=10800, help_text='Thời gian Practice (giây)'),
        ),
        migrations.CreateModel(
            name='ContestEditorialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('contest_hidden', 'Hide during contest'), ('show_after_contest', 'Show after contest ends'), ('show_only_free', 'Show free editorial during contest'), ('show_paid_only', 'Paid-only during contest')], default='contest_hidden', max_length=32)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_access_rules', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_editorial_rules', to='problems.problem')),
            ],
            options={
                'unique_together': {('contest', 'problem')},
            },
        ),
    ]
